import os

AWS_ACCOUNT = os.environ.get(
    "AWS_ACCOUNT", "638181072961"
)
AWS_REGION = os.environ.get("AWS_REGION", "eu-central-1")

AWS_DYNAMODB_TABLE_NAME = os.environ.get("AWS_DYNAMODB_TABLE_NAME", "Announcement")
AWS_DYNAMODB_READ_CAPACITY = int(os.environ.get("AWS_DYNAMODB_READ_CAPACITY", 5))
AWS_DYNAMODB_WRITE_CAPACITY = int(os.environ.get("AWS_DYNAMODB_WRITE_CAPACITY", 5))

AWS_LAMBDA_GET_ANNOUNCEMENT_RETRY_ATTEMPTS = int(
    os.environ.get("AWS_LAMBDA_GET_ANNOUNCEMENT_RETRY_ATTEMPTS", 0)
)
AWS_LAMBDA_CREATE_ANNOUNCEMENT_RETRY_ATTEMPTS = int(
    os.environ.get("AWS_LAMBDA_CREATE_ANNOUNCEMENT_RETRY_ATTEMPTS", 0)
)
