from .base import *

AWS_DYNAMODB_TABLE_NAME = "Dev-Announcement"
AWS_API_GATEWAY_APP_NAME = "Dev-AnnouncementAPI"
CORS_ALLOWED_ORIGINS = "*"

AWS_DYNAMODB_READ_CAPACITY = 1
AWS_DYNAMODB_WRITE_CAPACITY = 1

AWS_LAMBDA_GET_ANNOUNCEMENT_RETRY_ATTEMPTS = 1
AWS_LAMBDA_CREATE_ANNOUNCEMENT_RETRY_ATTEMPTS = 1
AWS_LAMBDA_GET_ANNOUNCEMENT_TIMEOUT = 2
AWS_LAMBDA_CREATE_ANNOUNCEMENT_TIMEOUT = 2
